apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: elastic-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"   # Passthrough for both
spec:
  rules:
    - host: kibana.sasa.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kb-quickstart-kb-http
                port:
                  number: 5601
    - host: fleet.sasa.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleet-server-agent-http
                port:
                  number: 8220