name: Deploy ELK Stack (ECK)

on:
  push:
    branches:
      - main
    paths:
      - 'elasticsearch/elasticsearch.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}

      - name: Verify kubectl access
        run: kubectl get nodes

      - name: Deploy Elasticsearch & Kibana & Fleet-server
        run: |
          kubectl apply -f elasticsearch/elasticsearch.yaml
          kubectl apply -f kibana/kibana.yaml
          kubectl apply -f elasticsearch/fleet-server/fleet-server.yaml

      - name: Success message
        run: echo "ðŸš€ ELK Stack deployed successfully!"